### ISSUE TITLE
org.exist.xmldb.RemoteCollection does not define or inherit an implementation

### ISSUE THREAD

**Issue by overdrive80** [xmldb-org/xmldb-api#166]
Hi, I am doing a maven project with existdb and xmldb.
These are the pom dependencies:

	<dependencies>
		
		<dependency>
			<groupId>org.exist-db</groupId>
			<artifactId>exist-core</artifactId>
			<version>6.2.0</version>
		</dependency>

		
		<dependency>
			<groupId>net.sf.xmldb-org</groupId>
			<artifactId>xmldb-api</artifactId>
			<version>2.0.0</version>
		</dependency>

	</dependencies>

I have existdb 6.2.0 installed. When I try to retrieve child collections from /db I get a listChildCollections method implementation error:

```Exception in thread "main" java.lang.AbstractMethodError: The receiver class org.exist.xmldb.RemoteCollection does not define or inherit an implementation of the abstract resolved method listChildCollections()Ljava/util/List; from the interface org.xmldb.api.base.Collection.```

Attached is a basic eclipse project for reproduction. [UT5_eXistdb.zip](https://github.com/xmldb-org/xmldb-api/files/14624911/UT5_eXistdb.zip)

![image](https://github.com/xmldb-org/xmldb-api/assets/1565083/5dde30a1-b83c-43d3-9853-08561a09ff40)

I have tested with version 1.7.0 and have had no problems, evidently because List is not used.

**Comment by reinhapa** [comment]
@overdrive80 the version 2.0.0 will be implemented by eXist 7.0.0 which is not yet released. eXist 6.2 does only support 1.x versions of the XMLDB API.

**Comment by overdrive80** [comment]
Sorry, I didn't know that. I searched but couldn't find anything about it. Thank you

**Comment by reinhapa** [comment]
No Problem
